import type { CarData } from './types';

export const CARS: CarData[] = [
  {
    id: 'twin-mill',
    name: 'Twin Mill',
    series: 'Original Sweet Sixteen',
    year: 1969,
    rarity: 'super-treasure',
    rarityScore: 5,
    description: 'The twin-engined legend that defined Hot Wheels. Two supercharged V8s mounted side by side, wrapped in a radical custom body that still turns heads after 50+ years.',
    specs: {
      engine: 'Twin Supercharged V8',
      horsepower: 1200,
      topSpeed: 240,
      weight: '3,400 lbs',
      scale: '1:64',
    },
    colors: ['Electric Blue', 'Chrome'],
    image: '/cars/twin-mill.png',
  },
  {
    id: 'bone-shaker',
    name: 'Bone Shaker',
    series: '2006 New Models',
    year: 2006,
    rarity: 'super-treasure',
    rarityScore: 5,
    description: 'A hot rod skull on wheels. The exposed engine, skeletal grille, and menacing stance make this one of the most iconic fantasy castings ever produced.',
    specs: {
      engine: 'Blown 426 Hemi',
      horsepower: 850,
      topSpeed: 195,
      weight: '2,800 lbs',
      scale: '1:64',
    },
    colors: ['Spectraflame Red', 'Skull White'],
    image: '/cars/bone-shaker.png',
  },
  {
    id: '67-camaro',
    name: "'67 Camaro",
    series: 'Muscle Mania',
    year: 2012,
    rarity: 'treasure',
    rarityScore: 4,
    description: 'The first-gen Camaro in its purest form. Rally stripes, rumbling 350 V8, and the unmistakable silhouette that launched a million drag races.',
    specs: {
      engine: '350 Small Block V8',
      horsepower: 375,
      topSpeed: 155,
      weight: '3,100 lbs',
      scale: '1:64',
    },
    colors: ['Racing Green', 'White Stripes'],
    image: '/cars/67-camaro.png',
  },
  {
    id: 'datsun-510',
    name: 'Datsun Bluebird 510',
    series: 'JDM Legends',
    year: 2018,
    rarity: 'treasure',
    rarityScore: 4,
    description: 'The Japanese underdog that conquered rally stages worldwide. Widebody fenders, a screaming L-series engine, and enough soul to make grown collectors weep.',
    specs: {
      engine: 'L18 Inline-4 Turbo',
      horsepower: 280,
      topSpeed: 145,
      weight: '2,200 lbs',
      scale: '1:64',
    },
    colors: ['Safari Brown', 'BRE livery'],
    image: '/cars/datsun-510.png',
  },
  {
    id: 'deora-ii',
    name: 'Deora II',
    series: 'Highway 35',
    year: 2003,
    rarity: 'limited',
    rarityScore: 3,
    description: 'A futuristic surf wagon designed by Nathan Proch. Won the Hot Wheels design contest and became a real life-size car. The dream made metal.',
    specs: {
      engine: 'Twin Turbo V6',
      horsepower: 450,
      topSpeed: 175,
      weight: '2,600 lbs',
      scale: '1:64',
    },
    colors: ['Pearl Orange', 'Metallic Silver'],
    image: '/cars/deora-ii.png',
  },
  {
    id: 'volkswagen-drag-bus',
    name: 'VW Drag Bus',
    series: 'Treasure Hunt',
    year: 1996,
    rarity: 'super-treasure',
    rarityScore: 5,
    description: 'A chopped, channeled, and drag-ready VW Bus. One of the most valuable Treasure Hunts ever produced. Finding one in the wild is like striking gold.',
    specs: {
      engine: 'Blown Flat-4',
      horsepower: 500,
      topSpeed: 165,
      weight: '2,400 lbs',
      scale: '1:64',
    },
    colors: ['Spectraflame Pink', 'Chrome Base'],
    image: '/cars/vw-drag-bus.png',
  },
  {
    id: 'nissan-skyline',
    name: 'Nissan Skyline GT-R (R34)',
    series: 'Fast & Furious',
    year: 2020,
    rarity: 'limited',
    rarityScore: 3,
    description: 'Godzilla in 1:64. The R34 GT-R in its most iconic blue, complete with Nismo aero and the legendary RB26DETT under the hood.',
    specs: {
      engine: 'RB26DETT Twin-Turbo I6',
      horsepower: 560,
      topSpeed: 190,
      weight: '3,200 lbs',
      scale: '1:64',
    },
    colors: ['Bayside Blue', 'Carbon Hood'],
    image: '/cars/nissan-skyline.png',
  },
  {
    id: 'porsche-356',
    name: 'Porsche 356A Outlaw',
    series: 'Car Culture',
    year: 2019,
    rarity: 'regular',
    rarityScore: 2,
    description: 'The Porsche that started it all, reimagined as a lowered outlaw with wider fenders and a meaner stance. Stuttgart meets the garage builder.',
    specs: {
      engine: 'Flat-4 Boxer',
      horsepower: 180,
      topSpeed: 130,
      weight: '1,800 lbs',
      scale: '1:64',
    },
    colors: ['Slate Grey', 'Rouge Interior'],
    image: '/cars/porsche-356.png',
  },
  {
    id: 'lamborghini-countach',
    name: 'Lamborghini Countach',
    series: 'Exotics',
    year: 2015,
    rarity: 'regular',
    rarityScore: 2,
    description: 'The poster car of the 1980s. Scissor doors, wedge profile, and a V12 soundtrack that defined an era of automotive excess.',
    specs: {
      engine: 'V12 5.2L',
      horsepower: 455,
      topSpeed: 183,
      weight: '3,000 lbs',
      scale: '1:64',
    },
    colors: ['Rosso Red', 'Black Accents'],
    image: '/cars/lamborghini-countach.png',
  },
  {
    id: 'batmobile-1966',
    name: '1966 TV Series Batmobile',
    series: 'Entertainment',
    year: 2014,
    rarity: 'limited',
    rarityScore: 3,
    description: 'Holy Hot Wheels, Batman! The Lincoln Futura-based Batmobile from the classic TV series, complete with jet exhaust and bat-insignia hubcaps.',
    specs: {
      engine: 'Atomic Turbine',
      horsepower: 900,
      topSpeed: 200,
      weight: '5,500 lbs',
      scale: '1:64',
    },
    colors: ['Gloss Black', 'Red Pinstripe'],
    image: '/cars/batmobile-1966.png',
  },
  {
    id: 'mazda-rx7',
    name: 'Mazda RX-7 (FD)',
    series: 'JDM Legends',
    year: 2021,
    rarity: 'treasure',
    rarityScore: 4,
    description: 'The rotary-powered masterpiece. Sequential twin turbos, perfect 50/50 weight distribution, and curves that belong in a museum.',
    specs: {
      engine: '13B-REW Twin-Rotor Turbo',
      horsepower: 320,
      topSpeed: 165,
      weight: '2,700 lbs',
      scale: '1:64',
    },
    colors: ['Brilliant Red', 'RE Amemiya Kit'],
    image: '/cars/mazda-rx7.png',
  },
  {
    id: 'ford-gt40',
    name: 'Ford GT-40',
    series: 'Race Day',
    year: 2017,
    rarity: 'regular',
    rarityScore: 2,
    description: 'Built with one mission: beat Ferrari at Le Mans. It did — four consecutive times. The GT40 is pure racing weaponry, rendered in miniature perfection.',
    specs: {
      engine: '7.0L V8',
      horsepower: 485,
      topSpeed: 210,
      weight: '2,200 lbs',
      scale: '1:64',
    },
    colors: ['Gulf Blue', 'Orange Stripes'],
    image: '/cars/ford-gt40.png',
  },
];
